#ifndef TMR_CONFIG_H_
#define TMR_CONFIG_H_

/* Options FOR TMR0 Mode:
1- TMR_TMR0_NORMAL_MODE
2- TMR_TMR0_CTC_MODE
3- TMR_TMR0_FAST_PWM_MODE
*/

#define TMR_TMR0_MODE             TMR_TMR0_CTC_MODE


#endif /* TMR_CONFIG_H_ */